site_name: SmartHome
theme:
  name: material
  logo: assets/logo.svg

plugins:
  - search
  - i18n:
      languages:
        - locale: en
          default: true
          name: English
        - locale: ru
          name: Русский
        - locale: es
          name: Español
        - locale: fr
          name: Français
