name: Deploy MkDocs
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - name: Install dependencies
        run: |
          pip install mkdocs mkdocs-material
      - name: Deploy
        run: |
          git config --global user.name "SmartHome Bot"
          git config --global user.email "bot@trifonov.me"
          mkdocs gh-deploy --force
